<style>
  .registration {
    margin: 30px;
  }

  .registration>form>div {
    margin: 16px 10px;
  }
</style>
<div class="registration">
  <h2>New User</h2>

  <hr>

  <form action="/users" method="post">
    <div>
      <label>
        ID:
        <input type="text" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
      </label>
    </div>
    <div>
      <label>
        Имя
        <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
      </label>
      <?php if (isset($errors['name'])) : ?>
        <div><?= $errors['name'] ?></div>
      <?php endif ?>
    </div>
    <div>
      <label>
        Email
        <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
      </label>
      <?php if (isset($errors['email'])) : ?>
        <div><?= $errors['email'] ?></div>
      <?php endif ?>
    </div>
    <input type="submit" value="Sign Up">
  </form>
  
  <hr>
</div>